-- LOOP â€” Catalogo de referencia (regiones, comunas, intereses)
-- Ejecutar DESPUES de loop_schema.sql via scripts/seed-catalogo.ps1
-- Re-ejecutable (on conflict do nothing / do update).

insert into public.region (nombre)
values
  ('Arica y Parinacota'),
  ('Tarapaca'),
  ('Antofagasta'),
  ('Atacama'),
  ('Coquimbo'),
  ('Valparaiso'),
  ('Metropolitana de Santiago'),
  ('O Higgins'),
  ('Maule'),
  ('Nuble'),
  ('Biobio'),
  ('La Araucania'),
  ('Los Rios'),
  ('Los Lagos'),
  ('Aysen'),
  ('Magallanes y de la Antartica Chilena')
on conflict (nombre) do nothing;

insert into public.comuna (nombre, region_id_region)
select v.nombre, r.id_region
from (values
  ('Arica', 'Arica y Parinacota'),
  ('Camarones', 'Arica y Parinacota'),
  ('Putre', 'Arica y Parinacota'),
  ('General Lagos', 'Arica y Parinacota'),
  ('Iquique', 'Tarapaca'),
  ('Alto Hospicio', 'Tarapaca'),
  ('Pozo Almonte', 'Tarapaca'),
  ('Antofagasta', 'Antofagasta'),
  ('Calama', 'Antofagasta'),
  ('Mejillones', 'Antofagasta'),
  ('Tocopilla', 'Antofagasta'),
  ('Copiapo', 'Atacama'),
  ('Caldera', 'Atacama'),
  ('Vallenar', 'Atacama'),
  ('Chanaral', 'Atacama'),
  ('La Serena', 'Coquimbo'),
  ('Coquimbo', 'Coquimbo'),
  ('Ovalle', 'Coquimbo'),
  ('Illapel', 'Coquimbo'),
  ('Valparaiso', 'Valparaiso'),
  ('Vina del Mar', 'Valparaiso'),
  ('Quilpue', 'Valparaiso'),
  ('San Antonio', 'Valparaiso'),
  ('Santiago', 'Metropolitana de Santiago'),
  ('Puente Alto', 'Metropolitana de Santiago'),
  ('Maipu', 'Metropolitana de Santiago'),
  ('Las Condes', 'Metropolitana de Santiago'),
  ('La Florida', 'Metropolitana de Santiago'),
  ('Providencia', 'Metropolitana de Santiago'),
  ('Nunoa', 'Metropolitana de Santiago'),
  ('Rancagua', 'O Higgins'),
  ('San Fernando', 'O Higgins'),
  ('Rengo', 'O Higgins'),
  ('Santa Cruz', 'O Higgins'),
  ('Talca', 'Maule'),
  ('Curico', 'Maule'),
  ('Linares', 'Maule'),
  ('Constitucion', 'Maule'),
  ('Chillan', 'Nuble'),
  ('San Carlos', 'Nuble'),
  ('Bulnes', 'Nuble'),
  ('Quillon', 'Nuble'),
  ('Concepcion', 'Biobio'),
  ('Talcahuano', 'Biobio'),
  ('Los Angeles', 'Biobio'),
  ('Chiguayante', 'Biobio'),
  ('Temuco', 'La Araucania'),
  ('Padre Las Casas', 'La Araucania'),
  ('Villarrica', 'La Araucania'),
  ('Angol', 'La Araucania'),
  ('Valdivia', 'Los Rios'),
  ('La Union', 'Los Rios'),
  ('Rio Bueno', 'Los Rios'),
  ('Panguipulli', 'Los Rios'),
  ('Puerto Montt', 'Los Lagos'),
  ('Osorno', 'Los Lagos'),
  ('Castro', 'Los Lagos'),
  ('Puerto Varas', 'Los Lagos'),
  ('Coyhaique', 'Aysen'),
  ('Aysen', 'Aysen'),
  ('Chile Chico', 'Aysen'),
  ('Cochrane', 'Aysen'),
  ('Punta Arenas', 'Magallanes y de la Antartica Chilena'),
  ('Puerto Natales', 'Magallanes y de la Antartica Chilena'),
  ('Porvenir', 'Magallanes y de la Antartica Chilena'),
  ('Cabo de Hornos', 'Magallanes y de la Antartica Chilena')
) as v(nombre, region_nombre)
inner join public.region r on r.nombre = v.region_nombre
on conflict (nombre, region_id_region) do nothing;

-- Semilla inicial basada en listado inicial de intereses
-- Nota: "icono" usa nombres tecnicos de Material Icons (en ingles).
-- Eso no afecta el idioma visual de la app, solo el identificador interno.
insert into public.intereses (categoria, nombre, slug, icono, color_hex)
values
  ('DEPORTE', 'Running', 'running', 'directions_run', '#0682BC'),
  ('DEPORTE', 'Atletismo', 'atletismo', 'timer', '#0682BC'),
  ('DEPORTE', 'Futbol', 'futbol', 'sports_soccer', '#0682BC'),
  ('DEPORTE', 'Basquetbol', 'basquetbol', 'sports_basketball', '#0682BC'),
  ('DEPORTE', 'Voleibol', 'voleibol', 'sports_volleyball', '#0682BC'),
  ('DEPORTE', 'Senderismo', 'senderismo', 'hiking', '#0682BC'),
  ('DEPORTE', 'Trekking', 'trekking', 'terrain', '#0682BC'),
  ('DEPORTE', 'Ciclismo', 'ciclismo', 'directions_bike', '#0682BC'),
  ('DEPORTE', 'Patinaje', 'patinaje', 'roller_skating', '#0682BC'),
  ('BIENESTAR', 'Yoga', 'yoga', 'self_improvement', '#0682BC'),
  ('BIENESTAR', 'Meditacion', 'meditacion', 'spa', '#0682BC'),
  ('DEPORTE', 'Boxeo', 'boxeo', 'sports_mma', '#0682BC'),
  ('DEPORTE', 'Karate', 'karate', 'sports_kabaddi', '#0682BC'),
  ('GASTRONOMIA', 'Gastronomia', 'gastronomia', 'restaurant', '#0682BC'),
  ('GASTRONOMIA', 'Cafeteria', 'cafeteria', 'coffee', '#0682BC'),
  ('GASTRONOMIA', 'Enologia', 'enologia', 'wine_bar', '#0682BC'),
  ('GASTRONOMIA', 'Cocteleria', 'cocteleria', 'local_bar', '#0682BC'),
  ('GASTRONOMIA', 'Cocina', 'cocina', 'soup_kitchen', '#0682BC'),
  ('GASTRONOMIA', 'Reposteria', 'reposteria', 'cake', '#0682BC'),
  ('GASTRONOMIA', 'Picnic', 'picnic', 'lunch_dining', '#0682BC'),
  ('CULTURA', 'Cine', 'cine', 'movie', '#0682BC'),
  ('CULTURA', 'Teatro', 'teatro', 'theaters', '#0682BC'),
  ('CULTURA', 'Conciertos', 'conciertos', 'music_note', '#0682BC'),
  ('CULTURA', 'Festivales', 'festivales', 'celebration', '#0682BC'),
  ('CULTURA', 'Museos', 'museos', 'museum', '#0682BC'),
  ('ARTE', 'Fotografia', 'fotografia', 'photo_camera', '#0682BC'),
  ('CULTURA', 'Lectura', 'lectura', 'menu_book', '#0682BC'),
  ('JUEGOS', 'Ajedrez', 'ajedrez', 'extension', '#0682BC'),
  ('JUEGOS', 'Billar', 'billar', 'sports', '#0682BC'),
  ('JUEGOS', 'Videojuegos', 'videojuegos', 'sports_esports', '#0682BC'),
  ('JUEGOS', 'Gaming', 'gaming', 'stadia_controller', '#0682BC'),
  ('BAILE', 'Salsa', 'salsa', 'music_note', '#0682BC'),
  ('BAILE', 'Bachata', 'bachata', 'music_note', '#0682BC'),
  ('JUEGOS', 'Trivia', 'trivia', 'quiz', '#0682BC'),
  ('ENTRETENCION', 'Karaoke', 'karaoke', 'mic', '#0682BC'),
  ('EDUCACION', 'Idiomas', 'idiomas', 'translate', '#0682BC'),
  ('ARTE', 'Ceramica', 'ceramica', 'palette', '#0682BC'),
  ('ARTE', 'Pintura', 'pintura', 'format_paint', '#0682BC'),
  ('ARTE', 'Costura', 'costura', 'content_cut', '#0682BC'),
  ('PROFESIONAL', 'Networking', 'networking', 'groups', '#0682BC'),
  ('PROFESIONAL', 'Emprendimiento', 'emprendimiento', 'lightbulb', '#0682BC'),
  ('PROFESIONAL', 'Debate', 'debate', 'record_voice_over', '#0682BC'),
  ('SOCIAL', 'Voluntariado', 'voluntariado', 'volunteer_activism', '#0682BC'),
  ('ESTILO_DE_VIDA', 'Mascotas', 'mascotas', 'pets', '#0682BC'),
  ('ESTILO_DE_VIDA', 'Viajes', 'viajes', 'flight', '#0682BC'),
  ('ESTILO_DE_VIDA', 'Campismo', 'campismo', 'camping', '#0682BC'),
  ('ESTILO_DE_VIDA', 'Jardineria', 'jardineria', 'yard', '#0682BC'),
  ('ESTILO_DE_VIDA', 'Bricolaje', 'bricolaje', 'handyman', '#0682BC'),
  ('CIENCIA', 'Astronomia', 'astronomia', 'nightlight', '#0682BC'),
  ('ARTE', 'Bisuteria', 'bisuteria', 'diamond', '#0682BC')
on conflict (slug) do update
set
  categoria = excluded.categoria,
  nombre = excluded.nombre,
  icono = excluded.icono,
  color_hex = excluded.color_hex,
  activo = true;
